name: Run Playwright Tests
on:
  push:
  pull_request:

jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-Python@v5
          with:
            python-version: "3.11"

        - name: Install dependencies
          run: |
            pip install -r requirements.txt
            python -m playwright install --with-deps

        - name: Recreate .env file from Github Secrets
          run:
            echo "SWAG_USERNAME=$SWAG_USERNAME" >> .env
            echo "SWAG_PASSWORD=$SWAG_PASSWORD" >> .env

        - name: Run Playwright script
          env:
            CI: true # this sets environment variable
          run: python Playwright/tests/test_saucedemo_purchase.py

